version: "3"
services:
  rest-number:
    image: "esdras/rest-number:native"
    ports:
      - "8701:8701"
  rest-book:
    image: "esdras/rest-book:native"
    ports:
      - "8702:8702"
    environment:
      - NUMBER_PROXY_MP_REST_URL=http://rest-number:8701
